server:
  port: 8098    #default port where the service will be started

spring:
  application:
    name: client-service   #current service name to be used by the eureka server

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    #leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: false
    lease:
      duration: 5




management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
